name: cicd
run-name: ${{ github.actor }} trigger publish libs workflow
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Europe/Paris

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pantsbuild/actions/init-pants@v4-scie-pants
        with:
          gha-cache-key: v0
          named-caches-hash: ${{ hashFiles('python-default.lock') }}
          cache-lmdb-store: 'false'

      - name: Check BUILD files
        run:  |
          pants tailor --check update-build-files --check ::

      - name: Lint
        run: | 
          pants lint ::

      - name: Test
        run: |
          pants test ::

      - name: Publish
        env:
          TWINE_USERNAME_PYPI: __token__
          TWINE_PASSWORD_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          pants publish ::
